# Generated by Django 3.0.14 on 2022-02-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='loaction',
            new_name='location',
        ),
    ]
