# Generated by Django 3.0.14 on 2022-02-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20220223_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
