# Generated by Django 3.0.14 on 2022-02-23 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20220223_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 23, 4, 3, 22, 790669, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
