# Generated by Django 3.0.14 on 2022-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='48px * 48px 크기의 png / jpg 파일을 업로드해주세요', max_length=6),
        ),
    ]
